name: Deploy to Staging

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: staging-deployment
  cancel-in-progress: false

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          echo "Deployment completed successfully"
        env:
          STAGING_URL: ${{ vars.STAGING_URL }}

  staging-success:
    name: Staging Deployment Success
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: always()
    steps:
      - name: Check staging deployment status
        run: |
          if [[ "${{ needs.deploy-staging.result }}" != "success" ]]; then
            echo "Staging deployment failed"
            exit 1
          fi
          echo "Staging deployment completed successfully"