name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Create release
        run: |
          echo "Creating release..."
          echo "Release created successfully"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-success:
    name: Release Success
    runs-on: ubuntu-latest
    needs: [release]
    if: always()
    steps:
      - name: Check release status
        run: |
          if [[ "${{ needs.release.result }}" != "success" ]]; then
            echo "Release failed"
            exit 1
          fi
          echo "Release completed successfully"