name: Secret Scanning

on:
  push:
    branches: [main, v5]
  pull_request:
    branches: [main, v5]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified --no-update --fail --github-actions
        env:
          # Enable smart scan detection to avoid scanning identical commits
          TRUFFLEHOG_SMART_SCAN: "true"

      - name: Upload TruffleHog results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: trufflehog-results
          path: |
            trufflehog-results.json
            trufflehog-results.sarif
          retention-days: 30

  secret-summary:
    name: Secret Scan Summary
    runs-on: ubuntu-latest
    needs: [secret-scan]
    if: always()
    steps:
      - name: Secret Scan Summary
        run: |
          echo "## Secret Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.secret-scan.result }}" == "success" ]]; then
            echo "✅ Secret Scanning: PASSED" >> $GITHUB_STEP_SUMMARY
            echo "No secrets detected in the codebase." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Secret Scanning: FAILED" >> $GITHUB_STEP_SUMMARY
            echo "Potential secrets detected. Please review the artifacts." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Secret scan completed on $(date)" >> $GITHUB_STEP_SUMMARY