name: Security Scan

on:
  push:
    branches: [main, v5]
  pull_request:
    branches: [main, v5]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level moderate || true

  security-success:
    name: Security Scan Success
    runs-on: ubuntu-latest
    needs: [dependency-scan]
    if: always()
    steps:
      - name: Check security scan status
        run: |
          if [[ "${{ needs.dependency-scan.result }}" != "success" ]]; then
            echo "Security scan failed"
            exit 1
          fi
          echo "Security scan completed successfully"